const analyzeBtn = document.querySelector(".analyze-btn");

if(analyzeBtn){

analyzeBtn.addEventListener("click", async ()=>{

let file = document.getElementById("fileInput").files[0];

if(!file){
alert("Please upload a soil image first");
return;
}

let formData = new FormData();
formData.append("image", file);

try{

let response = await fetch("http://127.0.0.1:5000/predict",{
method:"POST",
body:formData
});

let result = await response.json();

console.log(result);

/* Update scanner results */

document.getElementById("soilType").innerText = result.soil_type.replace("_"," ");
document.getElementById("moisture").innerText = result.moisture;
document.getElementById("strength").innerText = result.strength;
document.getElementById("crops").innerText = result.crops.join(", ");

document.getElementById("confidence").innerText = result.confidence + "%";
document.getElementById("healthScore").innerText = result.health_score + "/100";

/* Update hero section */

document.getElementById("heroSoil").innerText = result.soil_type.replace("_"," ");
document.getElementById("heroMoisture").innerText = result.moisture;
document.getElementById("heroStrength").innerText = result.strength;

/* Save results */

localStorage.setItem("soilType",result.soil_type);
localStorage.setItem("moisture",result.moisture);
localStorage.setItem("strength",result.strength);

/* Update dashboard */

updateDashboard(result.soil_type);

}
catch(error){
console.error(error);
alert("AI server not responding");
}

});

}


/* CAMERA FUNCTION */

async function openCamera(){

const video = document.getElementById("camera");

video.style.display="block";

let stream = await navigator.mediaDevices.getUserMedia({video:true});

video.srcObject = stream;

}


/* DOWNLOAD REPORT */

function downloadReport(){

let soil = localStorage.getItem("soilType");
let moisture = localStorage.getItem("moisture");
let strength = localStorage.getItem("strength");

let report = `
GeoAI Soil Intelligence Report

Soil Type: ${soil}
Moisture: ${moisture}
Strength: ${strength}

Generated by GeoAI Platform
`;

let blob = new Blob([report],{type:"text/plain"});
let link = document.createElement("a");

link.href = URL.createObjectURL(blob);
link.download="soil_report.txt";
link.click();

}


/* CHARTS */

let phChart;
let moistureChart;
let fertilityChart;

window.addEventListener("load",()=>{

const phCtx = document.getElementById("phChart");
const moistureCtx = document.getElementById("moistureChart");
const fertilityCtx = document.getElementById("fertilityChart");

phChart = new Chart(phCtx,{
type:"bar",
data:{
labels:["Nitrogen","Phosphorus","Potassium"],
datasets:[{
label:"Soil pH Composition",
data:[5,6,7],
backgroundColor:"#4CAF50"
}]
}
});

moistureChart = new Chart(moistureCtx,{
type:"doughnut",
data:{
labels:["Moisture","Dry"],
datasets:[{
data:[50,50],
backgroundColor:["#4CAF50","#222"]
}]
}
});

fertilityChart = new Chart(fertilityCtx,{
type:"radar",
data:{
labels:["Organic","Minerals","Water","Structure"],
datasets:[{
label:"Fertility Score",
data:[4,5,6,5],
backgroundColor:"rgba(76,175,80,0.3)",
borderColor:"#4CAF50"
}]
}
});

});


function updateDashboard(soil){

let phData = {
Alluvial_Soil:[6,7,5],
Arid_Soil:[8,6,4],
Black_Soil:[7,8,6],
Laterite_Soil:[5,6,4],
Mountain_Soil:[6,7,6],
Red_Soil:[5,6,5],
Yellow_Soil:[5,5,4]
};

let moistureData = {
Alluvial_Soil:70,
Arid_Soil:30,
Black_Soil:80,
Laterite_Soil:50,
Mountain_Soil:60,
Red_Soil:40,
Yellow_Soil:35
};

let fertilityData = {
Alluvial_Soil:[7,6,7,6],
Arid_Soil:[3,4,3,2],
Black_Soil:[8,7,8,7],
Laterite_Soil:[5,5,4,4],
Mountain_Soil:[6,6,5,5],
Red_Soil:[4,5,4,4],
Yellow_Soil:[3,4,3,3]
};

phChart.data.datasets[0].data = phData[soil];

moistureChart.data.datasets[0].data = [
moistureData[soil],
100-moistureData[soil]
];

fertilityChart.data.datasets[0].data = fertilityData[soil];

phChart.update();
moistureChart.update();
fertilityChart.update();

}
/* GEOAI MAP */

const map = L.map('soilMap').setView([20.5937, 78.9629], 5);

L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{
maxZoom:19
}).addTo(map);

map.on("click",function(e){

let lat = e.latlng.lat.toFixed(4);
let lon = e.latlng.lng.toFixed(4);

document.getElementById("mapLocation").innerText = lat + ", " + lon;

/* Dummy soil prediction for demo */

let soils = [
"Alluvial Soil",
"Black Soil",
"Red Soil",
"Laterite Soil",
"Arid Soil"
];

let randomSoil = soils[Math.floor(Math.random()*soils.length)];

document.getElementById("mapSoil").innerText = randomSoil;

});
function downloadReport(){

let soil = document.getElementById("soilType").innerText;
let moisture = document.getElementById("moisture").innerText;
let strength = document.getElementById("strength").innerText;
let confidence = document.getElementById("confidence").innerText;
let health = document.getElementById("healthScore").innerText;

let report = `
GeoAI Soil Intelligence Report

Soil Type: ${soil}
Moisture: ${moisture}
Strength: ${strength}
Confidence: ${confidence}
Health Score: ${health}

Generated by GeoAI Platform
`;

let blob = new Blob([report],{type:"text/plain"});
let link = document.createElement("a");

link.href = URL.createObjectURL(blob);
link.download="soil_report.txt";
link.click();

}