services:
  - type: web
    name: geoai-backend
    env: python
    buildCommand: "pip install --default-timeout=1000 --retries 5 -r backend/requirements.txt"
    startCommand: "uvicorn backend.app:app --host 0.0.0.0 --port 10000"